#sudo: false

language: cpp

notifications:
  slack: homedevworld:nQJuwptZIMX2Ajd0C8NnfTWc
  
compiler:
    - gcc

os:
  - linux

env:
    - QT_BASE=53
    - QT_BASE=54
    - QT_BASE=55
    - QT_BASE=56
    - QT_BASE=57

before_install:
#    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/pp
    - if [ "$CXX" = "g++" ]; then sudo add-apt-repository
      ppa:ubuntu-toolchain-r/test -y; fi
    - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository
      ppa:beineri/opt-qt532 -y; fi
    - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository
      ppa:beineri/opt-qt542 -y; fi
    - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository
      ppa:beineri/opt-qt551 -y; fi
    - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository 
      ppa:beineri/opt-qt562 -y; fi
    - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571 -y; fi
  
    - sudo apt-get update -qq
#    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev
#    libqt5webkit5-dev libsqlite3-dev - export
#    QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
    - sudo apt-get install g++-4.9 gcc-4.9
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9 gcc-4.9;
      export CXX="g++-4.9" CC="gcc-4.9"; $CXX --version; fi
    - if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base; source
      /opt/qt53/bin/qt53-env.sh; fi
    - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source
      /opt/qt54/bin/qt54-env.sh; fi
    - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base; source
      /opt/qt55/bin/qt55-env.sh; fi
    - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
    - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi


script:
    - cat /opt/qt$QT_BASE/mkspecs/linux-g++/qmake.conf
    - g++ --version
    - make --version
#    - qmake -qt=qt5 -v - qmake -qt=qt5
    - qmake systrayicon.pro -r -spec linux-g++ "CONFIG+=release"
    - sed -i "0,/RE/s/g++/$CXX/" Makefile
    - make
#    - make check
